#!/bin/bash
#
# copy the source tree over to the VCM user's space
# then change the file ownership to VCM and switch to tbeing the VCM user
#
sudo cp -R * /home/vcm/production
#
# copy the settings we don't want to keep in git into this directory
#
sudo cp /home/vcm/configs/env /home/vcm/production/.env
#
# make sure the pgadmin directory exists and has the correct ownership
#
sudo mkdir -p /home/vcm/production/pgadmin
#
sudo chown -R vcm /home/vcm/production
sudo chown -R 5050:5050 /home/vcm/production/pgadmin
#
# build the containers(s) using the production config
#
sudo docker-compose -f /home/vcm/production/docker-compose-production.yml build
