version: '3.8'
services:
  pgdatabase:
    image: 'postgres:16'
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - /home/vcm/development/rest-api-docker-compose/csv:/csv
    ports:
      - "5432:5432"
    env_file:
      - .env

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    env_file:
      - .env
    ports:
      - "8090:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - pgdatabase

  web:
    image: csv_heatmap-api
    build: "./"
    depends_on:
      - pgdatabase
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - ./csv:/csv
