#!/bin/bash
# 
sudo cd /home/vcm/production/rest-api-docker-compose
#
# if the containers were runnning before, shut them down
#
sudo docker-compose -f /home/vcm/production/rest-api-docker-compose/docker-compose-production.yml down
#
# run the containers(s) using the production config
#
sudo docker-compose -f /home/vcm/production/rest-api-docker-compose/docker-compose-production.yml up -d
