version: '3.8'
<<<<<<< HEAD
=======

>>>>>>> 3d7035e (Added Docker-compose production and development)
services:
  pgdatabase:
    image: 'postgres:16'
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
<<<<<<< HEAD
      - ./csv:/csv
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sm997postgres
      POSTGRES_PASSWORD: postgresduke
      POSTGRES_DB: postgres
    env_file:
      - .env
=======
    ports:
      - "5432:5432"
    env_file:
      - .env # environment file that holds usernames and passwords we want to keep out of git

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    env_file:
      - .env # environment file that holds usernames and passwords we want to keep out of git
    ports:
      - "8090:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - pgdatabase

  api:
    image: my-api
    build: "./"
    depends_on:
      - pgdatabase
    ports:
      - "8080:8080"
    env_file:
      - .env # environment file that holds settings for the API
    volumes:
      - ./app:/app

# Add wifi api stuff
>>>>>>> 3d7035e (Added Docker-compose production and development)

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    env_file:
      - .env
    ports:
      - "8090:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - pgdatabase

  web:
    image: csv-heatmap-api
    build: "./"
    depends_on:
      - pgdatabase
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - ./csv:/csv
